CREATE TABLE employee (
 id BIGINT(20) PRIMARY KEY NOT NULL COMMENT '主键',
 name VARCHAR(30) DEFAULT NULL COMMENT '姓名',
 age int(11) DEFAULT NULL COMMENT '年龄',
 email VARCHAR(30) DEFAULT NULL COMMENT '邮箱',
 manager_id BIGINT(20) DEFAULT NULL COMMENT '直属上级id',
 create_time DATETIME DEFAULT NULL COMMENT '创建时间',
 CONSTRAINT manager_fk FOREIGN KEY (manager_id) REFERENCES employee(id)
) ENGINE=INNODB CHARSET=UTF8;