server:
    port: 8082

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: root
#    password: test
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/robertdb?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: start01all
  log:

#    sql:
#      init:
#        schema-locations: classpath:db/schema-mysql.sql
#        data-locations: classpath:db/data-mysql.sql

logging:
  level:
    root: info
    com.example.springboot_mybatis.dao: trace
  pattern:
    console: '%p%m%n'
